name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  library-swift-latest:
  name: Library
  runs-on: macos-14
  strategy:
    matrix:
      config:
        - debug
        - release
  steps:
    - uses: actions/checkout@v4
    - name: Select Xcode 15.2
      run: sudo xcode-select -s /Applications/Xcode_15.2.app
        
    - name: Checkout Package
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: View Swift Version
      run: swift --version

    - name: Build and Test
      run: |
          swift build
          swift test
